@startuml interviewerPollCreating
left header
<font color=000 size=18><b>Package:</b> Specialist

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Name:</b> Create a new exercise.
<font color=000 size=16><b>Paticipants:</b> Specialist, System.
<font color=000 size=16><b>Prerequisites:</b> The user must be authorized in the system and have access to the capabilities of the appropriate tariff.
<font color=000 size=16><b>Result:</b> New exercise created.
<font color=000 size=16><b>Exeptions:</b>
<font color=000 size=16> EX_00: No access to database.

<font color=000 size=16><b>The main scenario:</b>

end header

|Specialist|
start
: The specialist goes to the section
"Create a new exercise".;
|System|
: The system gives the user access to
exercise designer.;

|Specialist|

: The user creates what he needs
survey with the help of a designer. ;

: The user clicks the "Create" button. ;

|System|

: The system creates a corresponding exercise and writes it to the database,
assigns it an index and provides the specialist with a link to it.;

note right #aaffaa
<font color=red><b> Maybe EX_00.
end note

: The system notifies the user about
successful creation and publication of his exercise,
provides him with a link to the exercise. ;

|Specialist|

: The exercise was created, the specialist was informed,
has the ability to work with the exercise and provide access to it. ;


stop;

right footer


System dynamics. Model of precedents.
NTUU KPI named after I. Sikorsky
Kyiv-2020
end footer

@enduml
