 @startuml Privileges&Ban
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-5
<font color=000 size=16><b>Name:</b> Manipulation of user access rights.
<font color=000 size=16><b>Paticipants:</b> Administrator, System.
<font color=000 size=16><b>Prerequisites:</b> Users must be in the mode of specialist, patient.
<font color=000 size=16><b>Result:</b> Changing access rights to create a specific questionnaire.

<font color=000 size=16><b>Main scenario:</b>

end header

|User|
start
: The administrator goes to the "Questionnaires" tab;

|System|
: The system shows the questionnaires in which the user is involved;

|User|
: The administrator selects the required questionnaire;

|System|
: The system opens the edit mode for the administrator;

|User|
: In edit mode, the administrator clicks
       "View users" button;

|System|
: The system provides patients and specialists,
       involved in the selected questionnaire;

|User|
: The administrator selects one of the users;

|System|
: The system provides opportunities for interaction
     selected user with a profile;

|User|
: The administrator puts / unchecks nearby
   with points of viewing, analysis, editing
   questionnaire, also available field "Take access";

note left #aaffaa
"Take away access" means a ban
(next you can specify the reason for the ban)
or delete.
end note

|System|
: The system responds to those selected by the administrator
   access rights and changes user capabilities;

|User|
: The administrator can add a user (click "+");

|System|
: The system will open a window where you can select the mode
   user (patient / specialist / administrator)
   and select access rights for it;

|User|
stop;

right footer


System dynamics. Model of precedents.
NTUU KPI named after I. Sikorsky
Kyiv-2020
end footer

@enduml
